version: '3'

services:
  roadrunner:
    build:
      context: ./containers/roadrunner
      args:
        PHP_IMAGE_VERSION: 8.2.15-cli-alpine3.19
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
